# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run (event triggers) 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: # if want to push to any branch, just say push remove the branch stuff below. 
    branches: [ "main" ]
  # Will only be triggered if pull_request created only to "main"
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: # this work flow only has one job: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #specifying the operating system. Can set up multiple operating syste 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 # this is linking to a github repository

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: | #run more than one line e.g. install python, "\n" install poetry
          echo Add other actions to build,
          echo test, and deploy your project.
